name: "MIXTILE Z-Wave Region Configurator"
description: "MIXTILE Z-Wave Region Configurator add-on!"
version: "1.0.1"
slug: "mixtile_region"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: true
hassio_api: true
init: false
options:
  device: null
  bootloader_baudrate: "115200"
  flow_control: false
  rf_region: "Europe"
schema:
  device: device(subsystem=tty)?
  bootloader_baudrate: list(115200)
  rf_region: list(Europe|US|Australia/New Zealand|Hong Kong|Malaysia|India|Isarel|Russia|China|US LongRange|Japan|Korea)
  flow_control: bool?
stage: experimental
startup: once
boot: manual